#' Smart Helper: Ensure Grouped Data
#'
#' (Internal function, not exported)
#' Validates if the input is a frequency table or raw data. If it is raw data,
#' it builds the frequency table using the specified width and type choices.
#'
#' @param data A numeric vector or a pre-existing frequency data frame.
#' @param width Class interval width (optional).
#' @param type Grouping method: "exclusive" (default) or "inclusive".
#' @return A validated frequency data frame.
.ensure_grouped_df <- function(data, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)

  if (is.numeric(data) && !is.data.frame(data)) {
    # Dynamically build the table using the user's specific choices
    if (type == "exclusive") {
      return(group_exclusive_freq(data, width))
    } else {
      return(group_inclusive_freq(data, width))
    }
  } else if (is.data.frame(data) && all(c("Lower", "Upper", "Midpoint", "Frequency", "Cumulative_Frequency") %in% names(data))) {
    return(data)
  } else {
    stop("Input must be a numeric vector or a valid frequency data frame generated by this package.")
  }
}

#' Grouped Mean
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return Numeric mean
#' @export
group_mean <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  sum(df$Midpoint * df$Frequency) / sum(df$Frequency)
}

#' Grouped Percentile
#'
#' @param x Numeric vector OR frequency table
#' @param p Percentile to calculate (0 to 100)
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return Numeric percentile value
#' @export
group_percentile <- function(x, p, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  n <- sum(df$Frequency)
  target <- (p / 100) * n

  idx <- which(df$Cumulative_Frequency >= target)[1]

  L <- df$Lower[idx]
  f <- df$Frequency[idx]
  cf_prev <- ifelse(idx == 1, 0, df$Cumulative_Frequency[idx - 1])
  h <- df$Upper[idx] - df$Lower[idx]

  L + ((target - cf_prev) / f) * h
}

#' Grouped Median
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return numeric median
#' @export
group_median <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  group_percentile(x, 50, width, type)
}

#' Grouped Mode
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return numeric mode
#' @export
group_mode <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  i <- which.max(df$Frequency)

  L <- df$Lower[i]
  f1 <- df$Frequency[i]
  f0 <- ifelse(i == 1, 0, df$Frequency[i - 1])
  f2 <- ifelse(i == nrow(df), 0, df$Frequency[i + 1])
  h <- df$Upper[i] - df$Lower[i]

  denominator <- (2 * f1 - f0 - f2)
  if (denominator == 0) return(df$Midpoint[i])

  L + ((f1 - f0) / denominator) * h
}

#' Grouped Variance
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return numeric variance
#' @export
group_variance <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  m <- group_mean(df, width, type)
  n <- sum(df$Frequency)

  if (n <= 1) stop("Not enough data to calculate variance.")
  sum(df$Frequency * (df$Midpoint - m)^2) / (n - 1)
}

#' Grouped Standard Deviation
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return numeric sd
#' @export
group_sd <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  sqrt(group_variance(x, width, type))
}

#' Grouped Coefficient of Variation
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return CV percentage
#' @export
group_cv <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  (group_sd(x, width, type) / group_mean(x, width, type)) * 100
}

#' Grouped Five Number Summary
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return Named numeric vector
#' @export
group_five_number <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  active_df <- df[df$Frequency > 0, ]

  c(
    Min = min(active_df$Lower),
    Q1 = group_percentile(df, 25, width, type),
    Median = group_percentile(df, 50, width, type),
    Q3 = group_percentile(df, 75, width, type),
    Max = max(active_df$Upper)
  )
}

#' Grouped Outliers (Accurate Boxplot Rule)
#'
#' Detects outliers using the standard 1.5 * IQR Boxplot rule applied to
#' midpoints, matching base R precision.
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return Vector of outlying midpoints
#' @importFrom stats quantile
#' @export
group_outliers <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)

  approx_raw <- rep(df$Midpoint, df$Frequency)
  if (length(approx_raw) == 0) return(numeric(0))

  Q1 <- stats::quantile(approx_raw, 0.25, names = FALSE)
  Q3 <- stats::quantile(approx_raw, 0.75, names = FALSE)
  IQR_val <- Q3 - Q1

  lower_fence <- Q1 - 1.5 * IQR_val
  upper_fence <- Q3 + 1.5 * IQR_val

  # Find midpoints that cross the IQR boundaries
  outlying_midpoints <- df$Midpoint[df$Midpoint < lower_fence | df$Midpoint > upper_fence]
  return(outlying_midpoints)
}

#' Grouped Skewness
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return skewness
#' @export
group_skewness <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  m <- group_mean(df, width, type)
  s <- group_sd(df, width, type)
  sum(df$Frequency * ((df$Midpoint - m)/s)^3) / sum(df$Frequency)
}

#' Grouped Kurtosis
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return excess kurtosis
#' @export
group_kurtosis <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)
  m <- group_mean(df, width, type)
  s <- group_sd(df, width, type)
  sum(df$Frequency * ((df$Midpoint - m)/s)^4) / sum(df$Frequency) - 3
}

#' Comprehensive Grouped Description
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional)
#' @param type Grouping method: "exclusive" or "inclusive"
#' @return A detailed list of descriptive statistics
#' @export
group_describe <- function(x, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)
  df <- .ensure_grouped_df(x, width, type)

  list(
    frequency_table = df,
    mean = group_mean(df, width, type),
    median = group_median(df, width, type),
    mode = group_mode(df, width, type),
    variance = group_variance(df, width, type),
    sd = group_sd(df, width, type),
    cv = group_cv(df, width, type),
    five_number_summary = group_five_number(df, width, type),
    skewness = group_skewness(df, width, type),
    kurtosis = group_kurtosis(df, width, type),
    outliers = group_outliers(df, width, type)
  )
}

#' Remove Outliers from Grouped Frequency Table
#'
#' Safely handles raw data, summary lists, or frequency data frames by evaluating
#' class midpoints against the 1.5 * IQR boxplot fence rules.
#'
#' @param df Raw numeric data vector, list output from group_describe, or frequency table.
#' @param width Class interval width (optional, applied if raw numeric data is given).
#' @param type Grouping method: "exclusive" or "inclusive" (applied if raw data is given).
#' @return A recalculated frequency data frame with outlier classes removed.
#' @importFrom stats quantile
#' @export
remove_grouped_outliers <- function(df, width = NULL, type = c("exclusive", "inclusive")) {
  type <- match.arg(type)

  # 1. Extract the frequency table if a group_describe list was provided
  if (is.list(df) && "frequency_table" %in% names(df)) {
    df <- df$frequency_table
  } else if (is.numeric(df) && !is.data.frame(df)) {
    # Dynamically build the table using the user's specific width and type choices
    df <- .ensure_grouped_df(df, width, type)
  }

  # 2. Validation Check
  if(!is.data.frame(df) || !all(c("Midpoint", "Frequency") %in% names(df))) {
    stop("Input must be raw data, a frequency data frame, or the output from group_describe().")
  }

  # 3. Reconstruct approximate raw data points from midpoints to find IQR fences
  approx_raw <- rep(df$Midpoint, df$Frequency)
  if(length(approx_raw) == 0) return(df)

  Q1 <- stats::quantile(approx_raw, 0.25, names = FALSE)
  Q3 <- stats::quantile(approx_raw, 0.75, names = FALSE)
  IQR_val <- Q3 - Q1

  lower_fence <- Q1 - 1.5 * IQR_val
  upper_fence <- Q3 + 1.5 * IQR_val

  # 4. Drop rows where midpoints fall outside the fences
  filtered_df <- df[df$Midpoint >= lower_fence & df$Midpoint <= upper_fence, ]

  if(is.factor(filtered_df$Class)) {
    filtered_df$Class <- droplevels(filtered_df$Class)
  }

  # 5. Recalculate relative and cumulative frequencies safely for the remaining data
  filtered_df$Relative_Frequency <- filtered_df$Frequency / sum(filtered_df$Frequency)
  filtered_df$Cumulative_Frequency <- cumsum(filtered_df$Frequency)
  rownames(filtered_df) <- NULL

  return(filtered_df)
}
#' Data Cleansing and Diagnostic Summary
#'
#' Detects duplicates, removes them, and provides a missing value breakdown.
#' Now fully supports both data frames and single variables/vectors.
#'
#' @param x Target data frame or numeric/character vector
#' @return A list containing the diagnostic summary and the cleaned data
#' @export
data_diagnostics <- function(x) {
  # 1. Handle Single Vectors vs Data Frames intelligently
  is_vector_input <- is.atomic(x) && !is.data.frame(x)

  if (is_vector_input) {
    # Convert vector to a 1-column dataframe temporarily for analysis
    df <- data.frame(Variable = x, stringsAsFactors = FALSE)
  } else {
    df <- x
  }

  # 2. Duplicate Detection
  duplicate_rows <- sum(duplicated(df))

  # 3. Missing Value Summary (Column by Column)
  missing_summary <- data.frame(
    Variable = names(df),
    Missing_Count = sapply(df, function(col) sum(is.na(col))),
    Missing_Percentage = sapply(df, function(col) round((sum(is.na(col)) / nrow(df)) * 100, 2))
  )
  rownames(missing_summary) <- NULL

  # 4. Clean the Data (Remove Exact Duplicates safely)
  clean_df <- df[!duplicated(df), , drop = FALSE]

  # 5. Format output: if input was a vector, return a vector. If dataframe, return dataframe.
  if (is_vector_input) {
    clean_data <- clean_df[[1]]
  } else {
    clean_data <- clean_df
  }

  list(
    Total_Original_Records = nrow(df),
    Duplicates_Removed = duplicate_rows,
    Remaining_Unique_Records = nrow(clean_df),
    Missing_Values_Report = missing_summary,
    Cleaned_Data = clean_data
  )
}



#' Calculate a Weighted Mean
#'
#' Computes the weighted average of a numeric vector.
#'
#' @param x A numeric vector of values.
#' @param w A numeric vector of weights, the same length as x.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value representing the weighted mean.
#' @export
calc_weighted_mean <- function(x, w, na.rm = TRUE) {
  if (length(x) != length(w)) stop("Vectors 'x' and 'w' must be the same length.")

  if (na.rm) {
    valid_indices <- !is.na(x) & !is.na(w)
    x <- x[valid_indices]
    w <- w[valid_indices]
  }

  return(sum(x * w) / sum(w))
}



#' Calculate a Weighted Standard Deviation
#'
#' Computes the weighted standard deviation of a numeric vector.
#'
#' @param x A numeric vector of values.
#' @param w A numeric vector of weights, the same length as x.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value representing the weighted standard deviation.
#' @export
calc_weighted_sd <- function(x, w, na.rm = TRUE) {
  if (length(x) != length(w)) stop("Vectors 'x' and 'w' must be the same length.")

  if (na.rm) {
    valid_indices <- !is.na(x) & !is.na(w)
    x <- x[valid_indices]
    w <- w[valid_indices]
  }

  w_mean <- sum(x * w) / sum(w)

  # Reliability weight correction for sample variance
  variance <- sum(w * (x - w_mean)^2) /
    (sum(w) - (sum(w^2) / sum(w)))

  return(sqrt(variance))
}



#' Calculate Geometric Mean
#'
#' Computes the geometric mean of a numeric vector. Highly useful for rates of change.
#'
#' @param x A numeric vector. All values must be strictly positive.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_geometric_mean <- function(x, na.rm = TRUE) {
  if (na.rm) x <- x[!is.na(x)]

  if (any(x <= 0)) {
    warning("Geometric mean requires strictly positive numbers. Non-positive values found.")
    return(NaN)
  }

  # Calculated using log transformation to prevent arithmetic overflow on large datasets
  return(exp(mean(log(x))))
}



#' Calculate Harmonic Mean
#'
#' Computes the harmonic mean of a numeric vector.
#'
#' @param x A numeric vector. All values must be strictly positive.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_harmonic_mean <- function(x, na.rm = TRUE) {
  if (na.rm) x <- x[!is.na(x)]

  if (any(x <= 0)) {
    warning("Harmonic mean requires strictly positive numbers. Non-positive values found.")
    return(NaN)
  }

  return(1 / mean(1 / x))
}



#' Calculate Trimmed Mean
#'
#' Computes the mean of a numeric vector after discarding a specified percentage
#' of the highest and lowest values to reduce the effect of outliers.
#'
#' @param x A numeric vector.
#' @param trim A fraction (0 to 0.5) of observations to be trimmed from each end. Defaults to 0.10 (10%).
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_trimmed_mean <- function(x, trim = 0.10, na.rm = TRUE) {
  if (trim < 0 || trim >= 0.5) {
    stop("Trim fraction must be between 0 and 0.499.")
  }

  # Utilizes base R's internal trim logic for optimized speed
  return(mean(x, trim = trim, na.rm = na.rm))
}
