#' Smart Helper: Ensure Grouped Data
#'
#' (Internal function, not exported)
#' Checks if input is raw data or a table. Converts raw data to a table automatically.
#'
#' @param data The input numeric vector or frequency table to check.
#' @return A validated frequency data frame.
.ensure_grouped_df <- function(data) {
  if (is.numeric(data)) {
    # If raw data, convert using our previously built function
    return(group_exclusive_freq(data))
  } else if (is.data.frame(data) && all(c("Lower", "Upper", "Midpoint", "Frequency", "Cumulative_Frequency") %in% names(data))) {
    return(data)
  } else {
    stop("Input must be a numeric vector or a valid frequency data frame generated by this package.")
  }
}

#' Grouped Mean
#'
#' Computes mean from grouped frequency distribution or raw data.
#'
#' @param x Numeric vector OR frequency table
#' @return Numeric mean
#' @export
group_mean <- function(x) {
  df <- .ensure_grouped_df(x)
  sum(df$Midpoint * df$Frequency) / sum(df$Frequency)
}

#' Grouped Percentile (Helper for Median and Quartiles)
#'
#' Calculates any percentile for grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @param p Percentile to calculate (0 to 100)
#' @return Numeric percentile value
#' @export
group_percentile <- function(x, p) {
  df <- .ensure_grouped_df(x)
  n <- sum(df$Frequency)
  target <- (p / 100) * n

  idx <- which(df$Cumulative_Frequency >= target)[1]

  L <- df$Lower[idx]
  f <- df$Frequency[idx]
  cf_prev <- ifelse(idx == 1, 0, df$Cumulative_Frequency[idx - 1])
  h <- df$Upper[idx] - df$Lower[idx]

  L + ((target - cf_prev) / f) * h
}

#' Grouped Median
#'
#' Estimates median from grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @return numeric median
#' @export
group_median <- function(x) {
  group_percentile(x, 50)
}

#' Grouped Mode
#'
#' Estimates mode from grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @return numeric mode
#' @export
group_mode <- function(x) {
  df <- .ensure_grouped_df(x)
  i <- which.max(df$Frequency)

  L <- df$Lower[i]
  f1 <- df$Frequency[i]
  f0 <- ifelse(i == 1, 0, df$Frequency[i - 1])
  f2 <- ifelse(i == nrow(df), 0, df$Frequency[i + 1])
  h <- df$Upper[i] - df$Lower[i]

  # Prevent division by zero if all frequencies are the same
  denominator <- (2 * f1 - f0 - f2)
  if (denominator == 0) return(df$Midpoint[i])

  L + ((f1 - f0) / denominator) * h
}

#' Grouped Variance
#'
#' Computes sample variance from grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @return numeric variance
#' @export
group_variance <- function(x) {
  df <- .ensure_grouped_df(x)
  m <- group_mean(df)
  n <- sum(df$Frequency)

  if (n <= 1) stop("Not enough data to calculate variance.")

  sum(df$Frequency * (df$Midpoint - m)^2) / (n - 1)
}

#' Grouped Standard Deviation
#'
#' Computes standard deviation from grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @return numeric sd
#' @export
group_sd <- function(x) {
  sqrt(group_variance(x))
}

#' Grouped Coefficient of Variation
#'
#' @param x Numeric vector OR frequency table
#' @return CV percentage
#' @export
group_cv <- function(x) {
  (group_sd(x) / group_mean(x)) * 100
}

#' Grouped Five Number Summary
#'
#' Calculates Min, Q1, Median, Q3, and Max for grouped data.
#'
#' @param x Numeric vector OR frequency table
#' @return Named numeric vector
#' @export
group_five_number <- function(x) {
  df <- .ensure_grouped_df(x)

  # Filter out classes with zero frequency for accurate Min/Max
  active_df <- df[df$Frequency > 0, ]

  c(
    Min = min(active_df$Lower),
    Q1 = group_percentile(df, 25),
    Median = group_percentile(df, 50),
    Q3 = group_percentile(df, 75),
    Max = max(active_df$Upper)
  )
}

#' Grouped Outliers
#'
#' Detects outliers using mean ± 2SD rule based on midpoints.
#'
#' @param x Numeric vector OR frequency table
#' @return Vector of outlying midpoints
#' @export
group_outliers <- function(x) {
  df <- .ensure_grouped_df(x)
  m <- group_mean(df)
  s <- group_sd(df)

  # Return midpoints that fall outside 2 standard deviations
  df$Midpoint[df$Midpoint < (m - 2*s) | df$Midpoint > (m + 2*s)]
}

#' Grouped Skewness
#'
#' @param x Numeric vector OR frequency table
#' @return skewness
#' @export
group_skewness <- function(x) {
  df <- .ensure_grouped_df(x)
  m <- group_mean(df)
  s <- group_sd(df)

  sum(df$Frequency * ((df$Midpoint - m)/s)^3) / sum(df$Frequency)
}

#' Grouped Kurtosis
#'
#' @param x Numeric vector OR frequency table
#' @return excess kurtosis
#' @export
group_kurtosis <- function(x) {
  df <- .ensure_grouped_df(x)
  m <- group_mean(df)
  s <- group_sd(df)

  # Excess kurtosis (subtracting 3)
  sum(df$Frequency * ((df$Midpoint - m)/s)^4) / sum(df$Frequency) - 3
}

#' Comprehensive Grouped Description
#'
#' Generates all descriptive statistics for a dataset.
#'
#' @param x Numeric vector OR frequency table
#' @param width Class interval width (optional, only used if x is raw data)
#' @return A detailed list of descriptive statistics
#' @export
group_describe <- function(x, width = NULL) {
  # Generate the table (using the exclusive freq function we built earlier)
  if (is.numeric(x)) {
    df <- group_exclusive_freq(x, width)
  } else {
    df <- .ensure_grouped_df(x)
  }

  list(
    frequency_table = df,
    mean = group_mean(df),
    median = group_median(df),
    mode = group_mode(df),
    variance = group_variance(df),
    sd = group_sd(df),
    cv = group_cv(df),
    five_number_summary = group_five_number(df),
    skewness = group_skewness(df),
    kurtosis = group_kurtosis(df),
    outliers = group_outliers(df)
  )
}

#' Remove Outliers from Grouped Frequency Table
#'
#' Removes classes from a frequency table that fall outside the 1.5 * IQR
#' range based on class midpoints, then recalculates relative and cumulative frequencies.
#'
#' @param df A data frame generated by group_exclusive_freq or group_inclusive_freq
#' @return A recalculated data frame with outlier classes removed
#' @export
remove_grouped_outliers <- function(df) {
  if(!is.data.frame(df) || !all(c("Midpoint", "Frequency") %in% names(df))) {
    stop("Input must be a frequency data frame with 'Midpoint' and 'Frequency' columns.")
  }

  # Reconstruct approximate raw data using midpoints to find IQR fences
  approx_raw <- rep(df$Midpoint, df$Frequency)

  # If table is empty or has no frequency, return as is
  if(length(approx_raw) == 0) return(df)

  # FIXED: Added stats:: back to avoid global variable notes
  Q1 <- stats::quantile(approx_raw, 0.25, names = FALSE)
  Q3 <- stats::quantile(approx_raw, 0.75, names = FALSE)
  IQR_val <- Q3 - Q1

  lower_fence <- Q1 - 1.5 * IQR_val
  upper_fence <- Q3 + 1.5 * IQR_val

  # Filter out rows where the midpoint is an outlier
  filtered_df <- df[df$Midpoint >= lower_fence & df$Midpoint <= upper_fence, ]

  # Drop empty factor levels if Class is a factor
  if(is.factor(filtered_df$Class)) {
    filtered_df$Class <- droplevels(filtered_df$Class)
  }

  # Recalculate frequencies since total N has changed
  filtered_df$Relative_Frequency <- filtered_df$Frequency / sum(filtered_df$Frequency)
  filtered_df$Cumulative_Frequency <- cumsum(filtered_df$Frequency)

  # Reset row names for clean output
  rownames(filtered_df) <- NULL

  return(filtered_df)
}
#' Data Cleansing and Diagnostic Summary
#'
#' Detects duplicates, removes them, and provides a missing value breakdown.
#'
#' @param df target dataframe
#' @return A list containing the diagnostic summary and the cleaned dataframe
#' @export
data_diagnostics <- function(df) {
  # 1. Duplicate Detection
  duplicate_rows <- sum(duplicated(df))

  # 2. Missing Value Summary (Column by Column)
  missing_summary <- data.frame(
    Variable = names(df),
    Missing_Count = sapply(df, function(x) sum(is.na(x))),
    Missing_Percentage = sapply(df, function(x) round((sum(is.na(x)) / nrow(df)) * 100, 2))
  )
  rownames(missing_summary) <- NULL

  # 3. Clean the Data (Remove Exact Duplicates)
  clean_df <- df[!duplicated(df), ]

  list(
    Total_Rows_Original = nrow(df),
    Duplicates_Detected_And_Removed = duplicate_rows,
    Missing_Values_Report = missing_summary,
    Cleaned_Data = clean_df
  )
}



#' Calculate a Weighted Mean
#'
#' Computes the weighted average of a numeric vector.
#'
#' @param x A numeric vector of values.
#' @param w A numeric vector of weights, the same length as x.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value representing the weighted mean.
#' @export
calc_weighted_mean <- function(x, w, na.rm = TRUE) {
  if (length(x) != length(w)) stop("Vectors 'x' and 'w' must be the same length.")

  if (na.rm) {
    valid_indices <- !is.na(x) & !is.na(w)
    x <- x[valid_indices]
    w <- w[valid_indices]
  }

  return(sum(x * w) / sum(w))
}



#' Calculate a Weighted Standard Deviation
#'
#' Computes the weighted standard deviation of a numeric vector.
#'
#' @param x A numeric vector of values.
#' @param w A numeric vector of weights, the same length as x.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value representing the weighted standard deviation.
#' @export
calc_weighted_sd <- function(x, w, na.rm = TRUE) {
  if (length(x) != length(w)) stop("Vectors 'x' and 'w' must be the same length.")

  if (na.rm) {
    valid_indices <- !is.na(x) & !is.na(w)
    x <- x[valid_indices]
    w <- w[valid_indices]
  }

  w_mean <- sum(x * w) / sum(w)

  # Reliability weight correction for sample variance
  variance <- sum(w * (x - w_mean)^2) /
    (sum(w) - (sum(w^2) / sum(w)))

  return(sqrt(variance))
}



#' Calculate Geometric Mean
#'
#' Computes the geometric mean of a numeric vector. Highly useful for rates of change.
#'
#' @param x A numeric vector. All values must be strictly positive.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_geometric_mean <- function(x, na.rm = TRUE) {
  if (na.rm) x <- x[!is.na(x)]

  if (any(x <= 0)) {
    warning("Geometric mean requires strictly positive numbers. Non-positive values found.")
    return(NaN)
  }

  # Calculated using log transformation to prevent arithmetic overflow on large datasets
  return(exp(mean(log(x))))
}



#' Calculate Harmonic Mean
#'
#' Computes the harmonic mean of a numeric vector.
#'
#' @param x A numeric vector. All values must be strictly positive.
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_harmonic_mean <- function(x, na.rm = TRUE) {
  if (na.rm) x <- x[!is.na(x)]

  if (any(x <= 0)) {
    warning("Harmonic mean requires strictly positive numbers. Non-positive values found.")
    return(NaN)
  }

  return(1 / mean(1 / x))
}



#' Calculate Trimmed Mean
#'
#' Computes the mean of a numeric vector after discarding a specified percentage
#' of the highest and lowest values to reduce the effect of outliers.
#'
#' @param x A numeric vector.
#' @param trim A fraction (0 to 0.5) of observations to be trimmed from each end. Defaults to 0.10 (10%).
#' @param na.rm Logical. Should missing values be removed? Defaults to TRUE.
#' @return A numeric value.
#' @export
calc_trimmed_mean <- function(x, trim = 0.10, na.rm = TRUE) {
  if (trim < 0 || trim >= 0.5) {
    stop("Trim fraction must be between 0 and 0.499.")
  }

  # Utilizes base R's internal trim logic for optimized speed
  return(mean(x, trim = trim, na.rm = na.rm))
}
