#' Grouped Exclusive Frequency Distribution
#'
#' Creates a frequency table with right-open intervals `[a, b)`.
#' Ideal for continuous data.
#'
#' @param x Numeric vector (raw data)
#' @param width Class interval width (optional)
#' @return Data frame
#' @export
group_exclusive_freq <- function(x, width = NULL) {
  if(!is.numeric(x)) stop("Input 'x' must be a numeric vector.")
  x <- na.omit(x)
  if(length(x) < 2) stop("Input must have at least 2 non-missing values.")

  if(is.null(width)){
    # Sturges' rule
    k <- ceiling(1 + 3.322 * log10(length(x)))
    width <- (max(x) - min(x)) / k
    # Use pretty() to get a clean, human-readable width
    width <- pretty(c(0, width))[2]
  }

  lower_bound <- floor(min(x) / width) * width
  upper_bound <- ceiling(max(x) / width) * width
  breaks <- seq(lower_bound, upper_bound + width, by = width)

  # Right = FALSE means intervals are [a, b)
  freq_table <- table(cut(x, breaks = breaks, right = FALSE, include.lowest = FALSE))

  lower <- head(breaks, -1)
  upper <- tail(breaks, -1)
  mid <- (lower + upper) / 2
  f <- as.numeric(freq_table)

  data.frame(
    Class = names(freq_table),
    Lower = lower,
    Upper = upper,
    Midpoint = mid,
    Frequency = f,
    Relative_Frequency = f / sum(f),
    Cumulative_Frequency = cumsum(f)
  )
}

#' Grouped Inclusive Frequency Distribution
#'
#' Creates a frequency table with closed intervals `[a, b]`.
#' Ideal for discrete/integer data.
#'
#' @param x Numeric vector (raw data)
#' @param width Class interval width (optional)
#' @return Data frame
#' @export
group_inclusive_freq <- function(x, width = NULL) {
  if(!is.numeric(x)) stop("Input 'x' must be a numeric vector.")
  x <- na.omit(round(x)) # Inclusive is typically for discrete/integer data
  if(length(x) < 2) stop("Input must have at least 2 non-missing values.")

  if(is.null(width)){
    k <- ceiling(1 + 3.322 * log10(length(x)))
    width <- ceiling((max(x) - min(x)) / k)
  }

  lower_bound <- floor(min(x) / width) * width
  breaks <- seq(lower_bound, max(x) + width, by = width)

  lower <- head(breaks, -1)
  upper <- tail(breaks, -1) - 1 # Subtract 1 for inclusive upper bound

  # Calculate exact midpoints based on true class boundaries
  true_lower <- lower - 0.5
  true_upper <- upper + 0.5
  mid <- (true_lower + true_upper) / 2

  class_labels <- paste0("[", lower, ",", upper, "]")

  # Bin the data manually to ensure strict inclusion
  f <- sapply(1:length(lower), function(i) {
    sum(x >= lower[i] & x <= upper[i])
  })

  data.frame(
    Class = class_labels,
    Lower = lower,
    Upper = upper,
    Midpoint = mid,
    Frequency = f,
    Relative_Frequency = f / sum(f),
    Cumulative_Frequency = cumsum(f)
  )
}

#' Grouped Descriptive Statistics
#'
#' Calculates the mean and standard deviation from grouped data.
#' Accepts either a raw numeric vector or a frequency data frame.
#'
#' @param data A numeric vector OR a dataframe output from group_exclusive_freq
#' @return A list containing Mean, Variance, and Standard Deviation
#' @export
group_desc_stats <- function(data) {
  if (is.numeric(data)) {
    df <- group_exclusive_freq(data)
  } else if (is.data.frame(data) && all(c("Midpoint", "Frequency") %in% names(data))) {
    df <- data
  } else {
    stop("Input must be a raw numeric vector or a grouped frequency data frame.")
  }

  n <- sum(df$Frequency)
  if(n <= 1) stop("Not enough data to calculate statistics.")

  g_mean <- sum(df$Midpoint * df$Frequency) / n
  g_var <- sum(df$Frequency * (df$Midpoint - g_mean)^2) / (n - 1)
  g_sd <- sqrt(g_var)

  list(
    Grouped_Mean = g_mean,
    Grouped_Variance = g_var,
    Grouped_SD = g_sd
  )
}


#' Remove Outliers from Grouped Frequency Table
#'
#' Removes classes from a frequency table that fall outside the 1.5 * IQR
#' range based on class midpoints. Automatically converts raw data to a
#' frequency table if provided.
#'
#' @param x A numeric vector (raw data) OR a frequency data frame
#' @return A recalculated data frame with outlier classes removed
#' @export
remove_grouped_outliers <- function(x) {
  # Smart Check: Convert raw data to a frequency table automatically
  if (is.numeric(x) && !is.data.frame(x)) {
    df <- group_exclusive_freq(x)
  } else if (is.data.frame(x) && all(c("Midpoint", "Frequency") %in% names(x))) {
    df <- x
  } else {
    stop("Input must be a raw numeric vector or a frequency data frame generated by this package.")
  }

  # Reconstruct approximate raw data based on midpoints to find quartiles
  approx_raw <- rep(df$Midpoint, df$Frequency)
  if(length(approx_raw) == 0) return(df)

  Q1 <- quantile(approx_raw, 0.25, names = FALSE)
  Q3 <- quantile(approx_raw, 0.75, names = FALSE)
  IQR_val <- Q3 - Q1

  lower_fence <- Q1 - 1.5 * IQR_val
  upper_fence <- Q3 + 1.5 * IQR_val

  # Filter out the classes that fall outside the fences
  filtered_df <- df[df$Midpoint >= lower_fence & df$Midpoint <= upper_fence, ]

  # Clean up factors if they exist
  if(is.factor(filtered_df$Class)) {
    filtered_df$Class <- droplevels(filtered_df$Class)
  }

  # Recalculate relative and cumulative frequencies for the new filtered table
  filtered_df$Relative_Frequency <- filtered_df$Frequency / sum(filtered_df$Frequency)
  filtered_df$Cumulative_Frequency <- cumsum(filtered_df$Frequency)
  rownames(filtered_df) <- NULL

  return(filtered_df)
}
